# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170830_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
