# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('section', models.IntegerField()),
                ('attendance_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
            ],
        ),
    ]
