# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_students_phone'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_attendance',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AddField(
            model_name='daily_attendance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='daily_attendance',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AlterField(
            model_name='daily_attendance',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Students'),
        ),
    ]
