# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20170920_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_attendance',
            name='student',
            field=models.CharField(max_length=500),
        ),
    ]
