# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='allmessages',
        ),
    ]
