# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20171002_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmessages',
            old_name='message',
            new_name='message_text',
        ),
    ]
