# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20171002_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmessages',
            name='m_to',
            field=models.CharField(max_length=500),
        ),
    ]
